Better code blocks
This commit adds some new functionality to code blocks. Firstly
it allows arbitrary delimiters meaning that code containing the
usual code block terminator can now be parsed correctly. The
syntax for this is:

    {delimiter@ocaml[ ... ]delimiter}

The delimiter can contain the chars `[ a-z A-Z 0-9 _ - ]`, the
same as the language tag that comes after the '@' symbol. Note
that there's no way to have a delimited code block without a
language tag.

The second piece of functionality is that code blocks can now have
associated output:

    {@ocaml[

    ... ocaml code ...

    ][

    ... odoc formatted output ...

    ]}

This syntax also supports the delimiters as above. The delimiters
only encode the _code_ block, not the output:

    {delim@ocaml[

    ... ocaml code containing ][ or ]} ...

    ]delim[

    ... odoc formatted output ...

    ]}

The idea is that the odoc formatted output should be well formed and thus
any escaping is done in the usual way.

The output can then contain, for example, error blocks produced by mdx:

    {delim@ocaml[
      let x = "]}
    ]delim[
    {err@mdx-error[
    Line 1, characters 9-10:
    Error: String literal not terminated]err}
    ]}

In addition this also allows the possibility of code blocks to produce
rich output - ie., allowing marked-up such as tables, headings,
images and so on, in such a way that they are associated with the code
block, and hence can be manipulated by a 'test-promote' workflow.